// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: attestux/v1/report.proto

package attestuxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationState int32

const (
	VerificationState_VERIFICATION_STATE_UNSPECIFIED VerificationState = 0
	VerificationState_VERIFICATION_STATE_VERIFIED    VerificationState = 1
	VerificationState_VERIFICATION_STATE_UNVERIFIED  VerificationState = 2
	VerificationState_VERIFICATION_STATE_FAILED      VerificationState = 3
)

// Enum value maps for VerificationState.
var (
	VerificationState_name = map[int32]string{
		0: "VERIFICATION_STATE_UNSPECIFIED",
		1: "VERIFICATION_STATE_VERIFIED",
		2: "VERIFICATION_STATE_UNVERIFIED",
		3: "VERIFICATION_STATE_FAILED",
	}
	VerificationState_value = map[string]int32{
		"VERIFICATION_STATE_UNSPECIFIED": 0,
		"VERIFICATION_STATE_VERIFIED":    1,
		"VERIFICATION_STATE_UNVERIFIED":  2,
		"VERIFICATION_STATE_FAILED":      3,
	}
)

func (x VerificationState) Enum() *VerificationState {
	p := new(VerificationState)
	*p = x
	return p
}

func (x VerificationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationState) Descriptor() protoreflect.EnumDescriptor {
	return file_attestux_v1_report_proto_enumTypes[0].Descriptor()
}

func (VerificationState) Type() protoreflect.EnumType {
	return &file_attestux_v1_report_proto_enumTypes[0]
}

func (x VerificationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationState.Descriptor instead.
func (VerificationState) EnumDescriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{0}
}

type EventDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	State         VerificationState      `protobuf:"varint,2,opt,name=state,proto3,enum=attestux.v1.VerificationState" json:"state,omitempty"`
	HashAlgorithm uint32                 `protobuf:"varint,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDigest) Reset() {
	*x = EventDigest{}
	mi := &file_attestux_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDigest) ProtoMessage() {}

func (x *EventDigest) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDigest.ProtoReflect.Descriptor instead.
func (*EventDigest) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *EventDigest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *EventDigest) GetState() VerificationState {
	if x != nil {
		return x.State
	}
	return VerificationState_VERIFICATION_STATE_UNSPECIFIED
}

func (x *EventDigest) GetHashAlgorithm() uint32 {
	if x != nil {
		return x.HashAlgorithm
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	PcrIndex      uint32                 `protobuf:"varint,2,opt,name=pcr_index,json=pcrIndex,proto3" json:"pcr_index,omitempty"`
	EventType     uint32                 `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventTypeName string                 `protobuf:"bytes,4,opt,name=event_type_name,json=eventTypeName,proto3" json:"event_type_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Decoded       string                 `protobuf:"bytes,6,opt,name=decoded,proto3" json:"decoded,omitempty"`
	Digests       []*EventDigest         `protobuf:"bytes,7,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_attestux_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Event) GetPcrIndex() uint32 {
	if x != nil {
		return x.PcrIndex
	}
	return 0
}

func (x *Event) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetEventTypeName() string {
	if x != nil {
		return x.EventTypeName
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetDecoded() string {
	if x != nil {
		return x.Decoded
	}
	return ""
}

func (x *Event) GetDigests() []*EventDigest {
	if x != nil {
		return x.Digests
	}
	return nil
}

type PcrResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pcr   *Pcr                   `protobuf:"bytes,1,opt,name=pcr,proto3" json:"pcr,omitempty"`
	// If replay succeeds with zero events, the PCR hasn't left its initial value.
	EventLogReplayed   bool   `protobuf:"varint,2,opt,name=event_log_replayed,json=eventLogReplayed,proto3" json:"event_log_replayed,omitempty"`
	HashAlgorithm      uint32 `protobuf:"varint,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	ReplayedEventCount uint32 `protobuf:"varint,4,opt,name=replayed_event_count,json=replayedEventCount,proto3" json:"replayed_event_count,omitempty"`
	// Replay needed synthetic events that weren't in the received log.
	ReplayUsedUnloggedEvents bool `protobuf:"varint,5,opt,name=replay_used_unlogged_events,json=replayUsedUnloggedEvents,proto3" json:"replay_used_unlogged_events,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PcrResult) Reset() {
	*x = PcrResult{}
	mi := &file_attestux_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcrResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcrResult) ProtoMessage() {}

func (x *PcrResult) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcrResult.ProtoReflect.Descriptor instead.
func (*PcrResult) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *PcrResult) GetPcr() *Pcr {
	if x != nil {
		return x.Pcr
	}
	return nil
}

func (x *PcrResult) GetEventLogReplayed() bool {
	if x != nil {
		return x.EventLogReplayed
	}
	return false
}

func (x *PcrResult) GetHashAlgorithm() uint32 {
	if x != nil {
		return x.HashAlgorithm
	}
	return 0
}

func (x *PcrResult) GetReplayedEventCount() uint32 {
	if x != nil {
		return x.ReplayedEventCount
	}
	return 0
}

func (x *PcrResult) GetReplayUsedUnloggedEvents() bool {
	if x != nil {
		return x.ReplayUsedUnloggedEvents
	}
	return false
}

type VerificationReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Pcrs           []*PcrResult           `protobuf:"bytes,2,rep,name=pcrs,proto3" json:"pcrs,omitempty"`
	Events         []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Warnings       []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Errors         []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	EvidenceSha256 []byte                 `protobuf:"bytes,6,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	TrustPolicy    TrustPolicy            `protobuf:"varint,7,opt,name=trust_policy,json=trustPolicy,proto3,enum=attestux.v1.TrustPolicy" json:"trust_policy,omitempty"`
	Status         VerificationStatus     `protobuf:"varint,8,opt,name=status,proto3,enum=attestux.v1.VerificationStatus" json:"status,omitempty"`
	// Parsing problems, bad entries, or report limits kept us from normalizing the full log.
	EventLogIncomplete bool `protobuf:"varint,9,opt,name=event_log_incomplete,json=eventLogIncomplete,proto3" json:"event_log_incomplete,omitempty"`
	// How many entries were left out, if we know the count.
	OmittedEventCount uint32 `protobuf:"varint,10,opt,name=omitted_event_count,json=omittedEventCount,proto3" json:"omitted_event_count,omitempty"`
	// SHA-256 of the accepted EK's canonical PKIX DER public key.
	EndorsementKeySha256 []byte `protobuf:"bytes,11,opt,name=endorsement_key_sha256,json=endorsementKeySha256,proto3" json:"endorsement_key_sha256,omitempty"`
	// Policy and format limitations that don't change from scan to scan.
	Limitations   []string `protobuf:"bytes,12,rep,name=limitations,proto3" json:"limitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationReport) Reset() {
	*x = VerificationReport{}
	mi := &file_attestux_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationReport) ProtoMessage() {}

func (x *VerificationReport) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationReport.ProtoReflect.Descriptor instead.
func (*VerificationReport) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *VerificationReport) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *VerificationReport) GetPcrs() []*PcrResult {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

func (x *VerificationReport) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *VerificationReport) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *VerificationReport) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *VerificationReport) GetEvidenceSha256() []byte {
	if x != nil {
		return x.EvidenceSha256
	}
	return nil
}

func (x *VerificationReport) GetTrustPolicy() TrustPolicy {
	if x != nil {
		return x.TrustPolicy
	}
	return TrustPolicy_TRUST_POLICY_UNSPECIFIED
}

func (x *VerificationReport) GetStatus() VerificationStatus {
	if x != nil {
		return x.Status
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *VerificationReport) GetEventLogIncomplete() bool {
	if x != nil {
		return x.EventLogIncomplete
	}
	return false
}

func (x *VerificationReport) GetOmittedEventCount() uint32 {
	if x != nil {
		return x.OmittedEventCount
	}
	return 0
}

func (x *VerificationReport) GetEndorsementKeySha256() []byte {
	if x != nil {
		return x.EndorsementKeySha256
	}
	return nil
}

func (x *VerificationReport) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

type VerificationCompletion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *VerificationReport    `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Receipt       *VerificationReceipt   `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationCompletion) Reset() {
	*x = VerificationCompletion{}
	mi := &file_attestux_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationCompletion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationCompletion) ProtoMessage() {}

func (x *VerificationCompletion) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationCompletion.ProtoReflect.Descriptor instead.
func (*VerificationCompletion) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *VerificationCompletion) GetReport() *VerificationReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *VerificationCompletion) GetReceipt() *VerificationReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type PendingVerification struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	Report              *VerificationReport            `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	ActivationChallenge *CredentialActivationChallenge `protobuf:"bytes,2,opt,name=activation_challenge,json=activationChallenge,proto3" json:"activation_challenge,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PendingVerification) Reset() {
	*x = PendingVerification{}
	mi := &file_attestux_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingVerification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingVerification) ProtoMessage() {}

func (x *PendingVerification) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingVerification.ProtoReflect.Descriptor instead.
func (*PendingVerification) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *PendingVerification) GetReport() *VerificationReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *PendingVerification) GetActivationChallenge() *CredentialActivationChallenge {
	if x != nil {
		return x.ActivationChallenge
	}
	return nil
}

type VerificationPreparation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*VerificationPreparation_Pending
	//	*VerificationPreparation_Completion
	Result        isVerificationPreparation_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationPreparation) Reset() {
	*x = VerificationPreparation{}
	mi := &file_attestux_v1_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationPreparation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationPreparation) ProtoMessage() {}

func (x *VerificationPreparation) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationPreparation.ProtoReflect.Descriptor instead.
func (*VerificationPreparation) Descriptor() ([]byte, []int) {
	return file_attestux_v1_report_proto_rawDescGZIP(), []int{6}
}

func (x *VerificationPreparation) GetResult() isVerificationPreparation_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VerificationPreparation) GetPending() *PendingVerification {
	if x != nil {
		if x, ok := x.Result.(*VerificationPreparation_Pending); ok {
			return x.Pending
		}
	}
	return nil
}

func (x *VerificationPreparation) GetCompletion() *VerificationCompletion {
	if x != nil {
		if x, ok := x.Result.(*VerificationPreparation_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isVerificationPreparation_Result interface {
	isVerificationPreparation_Result()
}

type VerificationPreparation_Pending struct {
	Pending *PendingVerification `protobuf:"bytes,1,opt,name=pending,proto3,oneof"`
}

type VerificationPreparation_Completion struct {
	Completion *VerificationCompletion `protobuf:"bytes,2,opt,name=completion,proto3,oneof"`
}

func (*VerificationPreparation_Pending) isVerificationPreparation_Result() {}

func (*VerificationPreparation_Completion) isVerificationPreparation_Result() {}

var File_attestux_v1_report_proto protoreflect.FileDescriptor

const file_attestux_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x18attestux/v1/report.proto\x12\vattestux.v1\x1a\x16attestux/v1/wire.proto\"\x82\x01\n" +
	"\vEventDigest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x124\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1e.attestux.v1.VerificationStateR\x05state\x12%\n" +
	"\x0ehash_algorithm\x18\x03 \x01(\rR\rhashAlgorithm\"\xe9\x01\n" +
	"\x05Event\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x1b\n" +
	"\tpcr_index\x18\x02 \x01(\rR\bpcrIndex\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\rR\teventType\x12&\n" +
	"\x0fevent_type_name\x18\x04 \x01(\tR\reventTypeName\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x18\n" +
	"\adecoded\x18\x06 \x01(\tR\adecoded\x122\n" +
	"\adigests\x18\a \x03(\v2\x18.attestux.v1.EventDigestR\adigests\"\xf5\x01\n" +
	"\tPcrResult\x12\"\n" +
	"\x03pcr\x18\x01 \x01(\v2\x10.attestux.v1.PcrR\x03pcr\x12,\n" +
	"\x12event_log_replayed\x18\x02 \x01(\bR\x10eventLogReplayed\x12%\n" +
	"\x0ehash_algorithm\x18\x03 \x01(\rR\rhashAlgorithm\x120\n" +
	"\x14replayed_event_count\x18\x04 \x01(\rR\x12replayedEventCount\x12=\n" +
	"\x1breplay_used_unlogged_events\x18\x05 \x01(\bR\x18replayUsedUnloggedEvents\"\x96\x04\n" +
	"\x12VerificationReport\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12*\n" +
	"\x04pcrs\x18\x02 \x03(\v2\x16.attestux.v1.PcrResultR\x04pcrs\x12*\n" +
	"\x06events\x18\x03 \x03(\v2\x12.attestux.v1.EventR\x06events\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12'\n" +
	"\x0fevidence_sha256\x18\x06 \x01(\fR\x0eevidenceSha256\x12;\n" +
	"\ftrust_policy\x18\a \x01(\x0e2\x18.attestux.v1.TrustPolicyR\vtrustPolicy\x127\n" +
	"\x06status\x18\b \x01(\x0e2\x1f.attestux.v1.VerificationStatusR\x06status\x120\n" +
	"\x14event_log_incomplete\x18\t \x01(\bR\x12eventLogIncomplete\x12.\n" +
	"\x13omitted_event_count\x18\n" +
	" \x01(\rR\x11omittedEventCount\x124\n" +
	"\x16endorsement_key_sha256\x18\v \x01(\fR\x14endorsementKeySha256\x12 \n" +
	"\vlimitations\x18\f \x03(\tR\vlimitations\"\x8d\x01\n" +
	"\x16VerificationCompletion\x127\n" +
	"\x06report\x18\x01 \x01(\v2\x1f.attestux.v1.VerificationReportR\x06report\x12:\n" +
	"\areceipt\x18\x02 \x01(\v2 .attestux.v1.VerificationReceiptR\areceipt\"\xad\x01\n" +
	"\x13PendingVerification\x127\n" +
	"\x06report\x18\x01 \x01(\v2\x1f.attestux.v1.VerificationReportR\x06report\x12]\n" +
	"\x14activation_challenge\x18\x02 \x01(\v2*.attestux.v1.CredentialActivationChallengeR\x13activationChallenge\"\xa8\x01\n" +
	"\x17VerificationPreparation\x12<\n" +
	"\apending\x18\x01 \x01(\v2 .attestux.v1.PendingVerificationH\x00R\apending\x12E\n" +
	"\n" +
	"completion\x18\x02 \x01(\v2#.attestux.v1.VerificationCompletionH\x00R\n" +
	"completionB\b\n" +
	"\x06result*\x9a\x01\n" +
	"\x11VerificationState\x12\"\n" +
	"\x1eVERIFICATION_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bVERIFICATION_STATE_VERIFIED\x10\x01\x12!\n" +
	"\x1dVERIFICATION_STATE_UNVERIFIED\x10\x02\x12\x1d\n" +
	"\x19VERIFICATION_STATE_FAILED\x10\x03B#\n" +
	"\x1fcom.github.attestux.protocol.v1P\x01b\x06proto3"

var (
	file_attestux_v1_report_proto_rawDescOnce sync.Once
	file_attestux_v1_report_proto_rawDescData []byte
)

func file_attestux_v1_report_proto_rawDescGZIP() []byte {
	file_attestux_v1_report_proto_rawDescOnce.Do(func() {
		file_attestux_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestux_v1_report_proto_rawDesc), len(file_attestux_v1_report_proto_rawDesc)))
	})
	return file_attestux_v1_report_proto_rawDescData
}

var file_attestux_v1_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attestux_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_attestux_v1_report_proto_goTypes = []any{
	(VerificationState)(0),                // 0: attestux.v1.VerificationState
	(*EventDigest)(nil),                   // 1: attestux.v1.EventDigest
	(*Event)(nil),                         // 2: attestux.v1.Event
	(*PcrResult)(nil),                     // 3: attestux.v1.PcrResult
	(*VerificationReport)(nil),            // 4: attestux.v1.VerificationReport
	(*VerificationCompletion)(nil),        // 5: attestux.v1.VerificationCompletion
	(*PendingVerification)(nil),           // 6: attestux.v1.PendingVerification
	(*VerificationPreparation)(nil),       // 7: attestux.v1.VerificationPreparation
	(*Pcr)(nil),                           // 8: attestux.v1.Pcr
	(TrustPolicy)(0),                      // 9: attestux.v1.TrustPolicy
	(VerificationStatus)(0),               // 10: attestux.v1.VerificationStatus
	(*VerificationReceipt)(nil),           // 11: attestux.v1.VerificationReceipt
	(*CredentialActivationChallenge)(nil), // 12: attestux.v1.CredentialActivationChallenge
}
var file_attestux_v1_report_proto_depIdxs = []int32{
	0,  // 0: attestux.v1.EventDigest.state:type_name -> attestux.v1.VerificationState
	1,  // 1: attestux.v1.Event.digests:type_name -> attestux.v1.EventDigest
	8,  // 2: attestux.v1.PcrResult.pcr:type_name -> attestux.v1.Pcr
	3,  // 3: attestux.v1.VerificationReport.pcrs:type_name -> attestux.v1.PcrResult
	2,  // 4: attestux.v1.VerificationReport.events:type_name -> attestux.v1.Event
	9,  // 5: attestux.v1.VerificationReport.trust_policy:type_name -> attestux.v1.TrustPolicy
	10, // 6: attestux.v1.VerificationReport.status:type_name -> attestux.v1.VerificationStatus
	4,  // 7: attestux.v1.VerificationCompletion.report:type_name -> attestux.v1.VerificationReport
	11, // 8: attestux.v1.VerificationCompletion.receipt:type_name -> attestux.v1.VerificationReceipt
	4,  // 9: attestux.v1.PendingVerification.report:type_name -> attestux.v1.VerificationReport
	12, // 10: attestux.v1.PendingVerification.activation_challenge:type_name -> attestux.v1.CredentialActivationChallenge
	6,  // 11: attestux.v1.VerificationPreparation.pending:type_name -> attestux.v1.PendingVerification
	5,  // 12: attestux.v1.VerificationPreparation.completion:type_name -> attestux.v1.VerificationCompletion
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_attestux_v1_report_proto_init() }
func file_attestux_v1_report_proto_init() {
	if File_attestux_v1_report_proto != nil {
		return
	}
	file_attestux_v1_wire_proto_init()
	file_attestux_v1_report_proto_msgTypes[6].OneofWrappers = []any{
		(*VerificationPreparation_Pending)(nil),
		(*VerificationPreparation_Completion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestux_v1_report_proto_rawDesc), len(file_attestux_v1_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestux_v1_report_proto_goTypes,
		DependencyIndexes: file_attestux_v1_report_proto_depIdxs,
		EnumInfos:         file_attestux_v1_report_proto_enumTypes,
		MessageInfos:      file_attestux_v1_report_proto_msgTypes,
	}.Build()
	File_attestux_v1_report_proto = out.File
	file_attestux_v1_report_proto_goTypes = nil
	file_attestux_v1_report_proto_depIdxs = nil
}
