// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: attestux/v1/wire.proto

package attestuxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationStatus int32

const (
	VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED        VerificationStatus = 0
	VerificationStatus_VERIFICATION_STATUS_PENDING_ACTIVATION VerificationStatus = 1
	VerificationStatus_VERIFICATION_STATUS_VERIFIED           VerificationStatus = 2
	VerificationStatus_VERIFICATION_STATUS_FAILED             VerificationStatus = 3
)

// Enum value maps for VerificationStatus.
var (
	VerificationStatus_name = map[int32]string{
		0: "VERIFICATION_STATUS_UNSPECIFIED",
		1: "VERIFICATION_STATUS_PENDING_ACTIVATION",
		2: "VERIFICATION_STATUS_VERIFIED",
		3: "VERIFICATION_STATUS_FAILED",
	}
	VerificationStatus_value = map[string]int32{
		"VERIFICATION_STATUS_UNSPECIFIED":        0,
		"VERIFICATION_STATUS_PENDING_ACTIVATION": 1,
		"VERIFICATION_STATUS_VERIFIED":           2,
		"VERIFICATION_STATUS_FAILED":             3,
	}
)

func (x VerificationStatus) Enum() *VerificationStatus {
	p := new(VerificationStatus)
	*p = x
	return p
}

func (x VerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_attestux_v1_wire_proto_enumTypes[0].Descriptor()
}

func (VerificationStatus) Type() protoreflect.EnumType {
	return &file_attestux_v1_wire_proto_enumTypes[0]
}

func (x VerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationStatus.Descriptor instead.
func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{0}
}

type TrustPolicy int32

const (
	TrustPolicy_TRUST_POLICY_UNSPECIFIED        TrustPolicy = 0
	TrustPolicy_TRUST_POLICY_NUVOTON            TrustPolicy = 1
	TrustPolicy_TRUST_POLICY_ATTESTUX_SIMULATOR TrustPolicy = 2
)

// Enum value maps for TrustPolicy.
var (
	TrustPolicy_name = map[int32]string{
		0: "TRUST_POLICY_UNSPECIFIED",
		1: "TRUST_POLICY_NUVOTON",
		2: "TRUST_POLICY_ATTESTUX_SIMULATOR",
	}
	TrustPolicy_value = map[string]int32{
		"TRUST_POLICY_UNSPECIFIED":        0,
		"TRUST_POLICY_NUVOTON":            1,
		"TRUST_POLICY_ATTESTUX_SIMULATOR": 2,
	}
)

func (x TrustPolicy) Enum() *TrustPolicy {
	p := new(TrustPolicy)
	*p = x
	return p
}

func (x TrustPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrustPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_attestux_v1_wire_proto_enumTypes[1].Descriptor()
}

func (TrustPolicy) Type() protoreflect.EnumType {
	return &file_attestux_v1_wire_proto_enumTypes[1]
}

func (x TrustPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrustPolicy.Descriptor instead.
func (TrustPolicy) EnumDescriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{1}
}

type ProtocolErrorCode int32

const (
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_UNSPECIFIED        ProtocolErrorCode = 0
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_UNEXPECTED_MESSAGE ProtocolErrorCode = 1
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_INVALID_CHALLENGE  ProtocolErrorCode = 2
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_ATTESTATION_FAILED ProtocolErrorCode = 3
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_INTERNAL           ProtocolErrorCode = 4
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_ACTIVATION_FAILED  ProtocolErrorCode = 5
	ProtocolErrorCode_PROTOCOL_ERROR_CODE_DEVICE_MISMATCH    ProtocolErrorCode = 6
)

// Enum value maps for ProtocolErrorCode.
var (
	ProtocolErrorCode_name = map[int32]string{
		0: "PROTOCOL_ERROR_CODE_UNSPECIFIED",
		1: "PROTOCOL_ERROR_CODE_UNEXPECTED_MESSAGE",
		2: "PROTOCOL_ERROR_CODE_INVALID_CHALLENGE",
		3: "PROTOCOL_ERROR_CODE_ATTESTATION_FAILED",
		4: "PROTOCOL_ERROR_CODE_INTERNAL",
		5: "PROTOCOL_ERROR_CODE_ACTIVATION_FAILED",
		6: "PROTOCOL_ERROR_CODE_DEVICE_MISMATCH",
	}
	ProtocolErrorCode_value = map[string]int32{
		"PROTOCOL_ERROR_CODE_UNSPECIFIED":        0,
		"PROTOCOL_ERROR_CODE_UNEXPECTED_MESSAGE": 1,
		"PROTOCOL_ERROR_CODE_INVALID_CHALLENGE":  2,
		"PROTOCOL_ERROR_CODE_ATTESTATION_FAILED": 3,
		"PROTOCOL_ERROR_CODE_INTERNAL":           4,
		"PROTOCOL_ERROR_CODE_ACTIVATION_FAILED":  5,
		"PROTOCOL_ERROR_CODE_DEVICE_MISMATCH":    6,
	}
)

func (x ProtocolErrorCode) Enum() *ProtocolErrorCode {
	p := new(ProtocolErrorCode)
	*p = x
	return p
}

func (x ProtocolErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_attestux_v1_wire_proto_enumTypes[2].Descriptor()
}

func (ProtocolErrorCode) Type() protoreflect.EnumType {
	return &file_attestux_v1_wire_proto_enumTypes[2]
}

func (x ProtocolErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolErrorCode.Descriptor instead.
func (ProtocolErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{2}
}

type AttestationChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationChallenge) Reset() {
	*x = AttestationChallenge{}
	mi := &file_attestux_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationChallenge) ProtoMessage() {}

func (x *AttestationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationChallenge.ProtoReflect.Descriptor instead.
func (*AttestationChallenge) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         []byte                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_attestux_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Quote) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *Quote) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Pcr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pcr) Reset() {
	*x = Pcr{}
	mi := &file_attestux_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pcr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pcr) ProtoMessage() {}

func (x *Pcr) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pcr.ProtoReflect.Descriptor instead.
func (*Pcr) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *Pcr) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Pcr) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type PcrBankEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashAlgorithm uint32                 `protobuf:"varint,1,opt,name=hash_algorithm,json=hashAlgorithm,proto3" json:"hash_algorithm,omitempty"`
	Quote         *Quote                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Pcrs          []*Pcr                 `protobuf:"bytes,3,rep,name=pcrs,proto3" json:"pcrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PcrBankEvidence) Reset() {
	*x = PcrBankEvidence{}
	mi := &file_attestux_v1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PcrBankEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcrBankEvidence) ProtoMessage() {}

func (x *PcrBankEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcrBankEvidence.ProtoReflect.Descriptor instead.
func (*PcrBankEvidence) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *PcrBankEvidence) GetHashAlgorithm() uint32 {
	if x != nil {
		return x.HashAlgorithm
	}
	return 0
}

func (x *PcrBankEvidence) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *PcrBankEvidence) GetPcrs() []*Pcr {
	if x != nil {
		return x.Pcrs
	}
	return nil
}

type EndorsementKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndorsementKey) Reset() {
	*x = EndorsementKey{}
	mi := &file_attestux_v1_wire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndorsementKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementKey) ProtoMessage() {}

func (x *EndorsementKey) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementKey.ProtoReflect.Descriptor instead.
func (*EndorsementKey) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{4}
}

func (x *EndorsementKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *EndorsementKey) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type AttestationEvidence struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AttestationPublic   []byte                 `protobuf:"bytes,1,opt,name=attestation_public,json=attestationPublic,proto3" json:"attestation_public,omitempty"`
	PcrBanks            []*PcrBankEvidence     `protobuf:"bytes,2,rep,name=pcr_banks,json=pcrBanks,proto3" json:"pcr_banks,omitempty"`
	EventLog            []byte                 `protobuf:"bytes,3,opt,name=event_log,json=eventLog,proto3" json:"event_log,omitempty"`
	AkCreateData        []byte                 `protobuf:"bytes,4,opt,name=ak_create_data,json=akCreateData,proto3" json:"ak_create_data,omitempty"`
	AkCreateAttestation []byte                 `protobuf:"bytes,5,opt,name=ak_create_attestation,json=akCreateAttestation,proto3" json:"ak_create_attestation,omitempty"`
	AkCreateSignature   []byte                 `protobuf:"bytes,6,opt,name=ak_create_signature,json=akCreateSignature,proto3" json:"ak_create_signature,omitempty"`
	EndorsementKeys     []*EndorsementKey      `protobuf:"bytes,7,rep,name=endorsement_keys,json=endorsementKeys,proto3" json:"endorsement_keys,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttestationEvidence) Reset() {
	*x = AttestationEvidence{}
	mi := &file_attestux_v1_wire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationEvidence) ProtoMessage() {}

func (x *AttestationEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationEvidence.ProtoReflect.Descriptor instead.
func (*AttestationEvidence) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{5}
}

func (x *AttestationEvidence) GetAttestationPublic() []byte {
	if x != nil {
		return x.AttestationPublic
	}
	return nil
}

func (x *AttestationEvidence) GetPcrBanks() []*PcrBankEvidence {
	if x != nil {
		return x.PcrBanks
	}
	return nil
}

func (x *AttestationEvidence) GetEventLog() []byte {
	if x != nil {
		return x.EventLog
	}
	return nil
}

func (x *AttestationEvidence) GetAkCreateData() []byte {
	if x != nil {
		return x.AkCreateData
	}
	return nil
}

func (x *AttestationEvidence) GetAkCreateAttestation() []byte {
	if x != nil {
		return x.AkCreateAttestation
	}
	return nil
}

func (x *AttestationEvidence) GetAkCreateSignature() []byte {
	if x != nil {
		return x.AkCreateSignature
	}
	return nil
}

func (x *AttestationEvidence) GetEndorsementKeys() []*EndorsementKey {
	if x != nil {
		return x.EndorsementKeys
	}
	return nil
}

type CredentialActivationChallenge struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EndorsementKeySha256 []byte                 `protobuf:"bytes,1,opt,name=endorsement_key_sha256,json=endorsementKeySha256,proto3" json:"endorsement_key_sha256,omitempty"`
	Credential           []byte                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	EncryptedSecret      []byte                 `protobuf:"bytes,3,opt,name=encrypted_secret,json=encryptedSecret,proto3" json:"encrypted_secret,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CredentialActivationChallenge) Reset() {
	*x = CredentialActivationChallenge{}
	mi := &file_attestux_v1_wire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialActivationChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialActivationChallenge) ProtoMessage() {}

func (x *CredentialActivationChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialActivationChallenge.ProtoReflect.Descriptor instead.
func (*CredentialActivationChallenge) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{6}
}

func (x *CredentialActivationChallenge) GetEndorsementKeySha256() []byte {
	if x != nil {
		return x.EndorsementKeySha256
	}
	return nil
}

func (x *CredentialActivationChallenge) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CredentialActivationChallenge) GetEncryptedSecret() []byte {
	if x != nil {
		return x.EncryptedSecret
	}
	return nil
}

type CredentialActivationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        []byte                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialActivationResponse) Reset() {
	*x = CredentialActivationResponse{}
	mi := &file_attestux_v1_wire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialActivationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialActivationResponse) ProtoMessage() {}

func (x *CredentialActivationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialActivationResponse.ProtoReflect.Descriptor instead.
func (*CredentialActivationResponse) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialActivationResponse) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type VerificationReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Errors         []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	EvidenceSha256 []byte                 `protobuf:"bytes,3,opt,name=evidence_sha256,json=evidenceSha256,proto3" json:"evidence_sha256,omitempty"`
	TrustPolicy    TrustPolicy            `protobuf:"varint,4,opt,name=trust_policy,json=trustPolicy,proto3,enum=attestux.v1.TrustPolicy" json:"trust_policy,omitempty"`
	Status         VerificationStatus     `protobuf:"varint,5,opt,name=status,proto3,enum=attestux.v1.VerificationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationReceipt) Reset() {
	*x = VerificationReceipt{}
	mi := &file_attestux_v1_wire_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationReceipt) ProtoMessage() {}

func (x *VerificationReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationReceipt.ProtoReflect.Descriptor instead.
func (*VerificationReceipt) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{8}
}

func (x *VerificationReceipt) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *VerificationReceipt) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *VerificationReceipt) GetEvidenceSha256() []byte {
	if x != nil {
		return x.EvidenceSha256
	}
	return nil
}

func (x *VerificationReceipt) GetTrustPolicy() TrustPolicy {
	if x != nil {
		return x.TrustPolicy
	}
	return TrustPolicy_TRUST_POLICY_UNSPECIFIED
}

func (x *VerificationReceipt) GetStatus() VerificationStatus {
	if x != nil {
		return x.Status
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ProtocolErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=attestux.v1.ProtocolErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_attestux_v1_wire_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{9}
}

func (x *ProtocolError) GetCode() ProtocolErrorCode {
	if x != nil {
		return x.Code
	}
	return ProtocolErrorCode_PROTOCOL_ERROR_CODE_UNSPECIFIED
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// One USB frame behind a big-endian u32 length. The payload limits are
// 32 MiB for evidence and 64 KiB for everything else.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Frame_Challenge
	//	*Frame_Evidence
	//	*Frame_ActivationChallenge
	//	*Frame_ActivationResponse
	//	*Frame_Receipt
	//	*Frame_Error
	Payload       isFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_attestux_v1_wire_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_attestux_v1_wire_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_attestux_v1_wire_proto_rawDescGZIP(), []int{10}
}

func (x *Frame) GetPayload() isFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetChallenge() *AttestationChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *Frame) GetEvidence() []byte {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Evidence); ok {
			return x.Evidence
		}
	}
	return nil
}

func (x *Frame) GetActivationChallenge() *CredentialActivationChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Frame_ActivationChallenge); ok {
			return x.ActivationChallenge
		}
	}
	return nil
}

func (x *Frame) GetActivationResponse() *CredentialActivationResponse {
	if x != nil {
		if x, ok := x.Payload.(*Frame_ActivationResponse); ok {
			return x.ActivationResponse
		}
	}
	return nil
}

func (x *Frame) GetReceipt() *VerificationReceipt {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *Frame) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Payload.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFrame_Payload interface {
	isFrame_Payload()
}

type Frame_Challenge struct {
	Challenge *AttestationChallenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type Frame_Evidence struct {
	// Encoded AttestationEvidence, kept intact for the receipt hash.
	Evidence []byte `protobuf:"bytes,2,opt,name=evidence,proto3,oneof"`
}

type Frame_ActivationChallenge struct {
	ActivationChallenge *CredentialActivationChallenge `protobuf:"bytes,3,opt,name=activation_challenge,json=activationChallenge,proto3,oneof"`
}

type Frame_ActivationResponse struct {
	ActivationResponse *CredentialActivationResponse `protobuf:"bytes,4,opt,name=activation_response,json=activationResponse,proto3,oneof"`
}

type Frame_Receipt struct {
	Receipt *VerificationReceipt `protobuf:"bytes,5,opt,name=receipt,proto3,oneof"`
}

type Frame_Error struct {
	Error *ProtocolError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*Frame_Challenge) isFrame_Payload() {}

func (*Frame_Evidence) isFrame_Payload() {}

func (*Frame_ActivationChallenge) isFrame_Payload() {}

func (*Frame_ActivationResponse) isFrame_Payload() {}

func (*Frame_Receipt) isFrame_Payload() {}

func (*Frame_Error) isFrame_Payload() {}

var File_attestux_v1_wire_proto protoreflect.FileDescriptor

const file_attestux_v1_wire_proto_rawDesc = "" +
	"\n" +
	"\x16attestux/v1/wire.proto\x12\vattestux.v1\",\n" +
	"\x14AttestationChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\";\n" +
	"\x05Quote\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\fR\x05quote\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"3\n" +
	"\x03Pcr\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"\x88\x01\n" +
	"\x0fPcrBankEvidence\x12%\n" +
	"\x0ehash_algorithm\x18\x01 \x01(\rR\rhashAlgorithm\x12(\n" +
	"\x05quote\x18\x02 \x01(\v2\x12.attestux.v1.QuoteR\x05quote\x12$\n" +
	"\x04pcrs\x18\x03 \x03(\v2\x10.attestux.v1.PcrR\x04pcrs\"Q\n" +
	"\x0eEndorsementKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\"\xee\x02\n" +
	"\x13AttestationEvidence\x12-\n" +
	"\x12attestation_public\x18\x01 \x01(\fR\x11attestationPublic\x129\n" +
	"\tpcr_banks\x18\x02 \x03(\v2\x1c.attestux.v1.PcrBankEvidenceR\bpcrBanks\x12\x1b\n" +
	"\tevent_log\x18\x03 \x01(\fR\beventLog\x12$\n" +
	"\x0eak_create_data\x18\x04 \x01(\fR\fakCreateData\x122\n" +
	"\x15ak_create_attestation\x18\x05 \x01(\fR\x13akCreateAttestation\x12.\n" +
	"\x13ak_create_signature\x18\x06 \x01(\fR\x11akCreateSignature\x12F\n" +
	"\x10endorsement_keys\x18\a \x03(\v2\x1b.attestux.v1.EndorsementKeyR\x0fendorsementKeys\"\xa0\x01\n" +
	"\x1dCredentialActivationChallenge\x124\n" +
	"\x16endorsement_key_sha256\x18\x01 \x01(\fR\x14endorsementKeySha256\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\fR\n" +
	"credential\x12)\n" +
	"\x10encrypted_secret\x18\x03 \x01(\fR\x0fencryptedSecret\"6\n" +
	"\x1cCredentialActivationResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\fR\x06secret\"\xe9\x01\n" +
	"\x13VerificationReceipt\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12'\n" +
	"\x0fevidence_sha256\x18\x03 \x01(\fR\x0eevidenceSha256\x12;\n" +
	"\ftrust_policy\x18\x04 \x01(\x0e2\x18.attestux.v1.TrustPolicyR\vtrustPolicy\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.attestux.v1.VerificationStatusR\x06status\"]\n" +
	"\rProtocolError\x122\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1e.attestux.v1.ProtocolErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa4\x03\n" +
	"\x05Frame\x12A\n" +
	"\tchallenge\x18\x01 \x01(\v2!.attestux.v1.AttestationChallengeH\x00R\tchallenge\x12\x1c\n" +
	"\bevidence\x18\x02 \x01(\fH\x00R\bevidence\x12_\n" +
	"\x14activation_challenge\x18\x03 \x01(\v2*.attestux.v1.CredentialActivationChallengeH\x00R\x13activationChallenge\x12\\\n" +
	"\x13activation_response\x18\x04 \x01(\v2).attestux.v1.CredentialActivationResponseH\x00R\x12activationResponse\x12<\n" +
	"\areceipt\x18\x05 \x01(\v2 .attestux.v1.VerificationReceiptH\x00R\areceipt\x122\n" +
	"\x05error\x18\x06 \x01(\v2\x1a.attestux.v1.ProtocolErrorH\x00R\x05errorB\t\n" +
	"\apayload*\xa7\x01\n" +
	"\x12VerificationStatus\x12#\n" +
	"\x1fVERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&VERIFICATION_STATUS_PENDING_ACTIVATION\x10\x01\x12 \n" +
	"\x1cVERIFICATION_STATUS_VERIFIED\x10\x02\x12\x1e\n" +
	"\x1aVERIFICATION_STATUS_FAILED\x10\x03*j\n" +
	"\vTrustPolicy\x12\x1c\n" +
	"\x18TRUST_POLICY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TRUST_POLICY_NUVOTON\x10\x01\x12#\n" +
	"\x1fTRUST_POLICY_ATTESTUX_SIMULATOR\x10\x02*\xb1\x02\n" +
	"\x11ProtocolErrorCode\x12#\n" +
	"\x1fPROTOCOL_ERROR_CODE_UNSPECIFIED\x10\x00\x12*\n" +
	"&PROTOCOL_ERROR_CODE_UNEXPECTED_MESSAGE\x10\x01\x12)\n" +
	"%PROTOCOL_ERROR_CODE_INVALID_CHALLENGE\x10\x02\x12*\n" +
	"&PROTOCOL_ERROR_CODE_ATTESTATION_FAILED\x10\x03\x12 \n" +
	"\x1cPROTOCOL_ERROR_CODE_INTERNAL\x10\x04\x12)\n" +
	"%PROTOCOL_ERROR_CODE_ACTIVATION_FAILED\x10\x05\x12'\n" +
	"#PROTOCOL_ERROR_CODE_DEVICE_MISMATCH\x10\x06B#\n" +
	"\x1fcom.github.attestux.protocol.v1P\x01b\x06proto3"

var (
	file_attestux_v1_wire_proto_rawDescOnce sync.Once
	file_attestux_v1_wire_proto_rawDescData []byte
)

func file_attestux_v1_wire_proto_rawDescGZIP() []byte {
	file_attestux_v1_wire_proto_rawDescOnce.Do(func() {
		file_attestux_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestux_v1_wire_proto_rawDesc), len(file_attestux_v1_wire_proto_rawDesc)))
	})
	return file_attestux_v1_wire_proto_rawDescData
}

var file_attestux_v1_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_attestux_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_attestux_v1_wire_proto_goTypes = []any{
	(VerificationStatus)(0),               // 0: attestux.v1.VerificationStatus
	(TrustPolicy)(0),                      // 1: attestux.v1.TrustPolicy
	(ProtocolErrorCode)(0),                // 2: attestux.v1.ProtocolErrorCode
	(*AttestationChallenge)(nil),          // 3: attestux.v1.AttestationChallenge
	(*Quote)(nil),                         // 4: attestux.v1.Quote
	(*Pcr)(nil),                           // 5: attestux.v1.Pcr
	(*PcrBankEvidence)(nil),               // 6: attestux.v1.PcrBankEvidence
	(*EndorsementKey)(nil),                // 7: attestux.v1.EndorsementKey
	(*AttestationEvidence)(nil),           // 8: attestux.v1.AttestationEvidence
	(*CredentialActivationChallenge)(nil), // 9: attestux.v1.CredentialActivationChallenge
	(*CredentialActivationResponse)(nil),  // 10: attestux.v1.CredentialActivationResponse
	(*VerificationReceipt)(nil),           // 11: attestux.v1.VerificationReceipt
	(*ProtocolError)(nil),                 // 12: attestux.v1.ProtocolError
	(*Frame)(nil),                         // 13: attestux.v1.Frame
}
var file_attestux_v1_wire_proto_depIdxs = []int32{
	4,  // 0: attestux.v1.PcrBankEvidence.quote:type_name -> attestux.v1.Quote
	5,  // 1: attestux.v1.PcrBankEvidence.pcrs:type_name -> attestux.v1.Pcr
	6,  // 2: attestux.v1.AttestationEvidence.pcr_banks:type_name -> attestux.v1.PcrBankEvidence
	7,  // 3: attestux.v1.AttestationEvidence.endorsement_keys:type_name -> attestux.v1.EndorsementKey
	1,  // 4: attestux.v1.VerificationReceipt.trust_policy:type_name -> attestux.v1.TrustPolicy
	0,  // 5: attestux.v1.VerificationReceipt.status:type_name -> attestux.v1.VerificationStatus
	2,  // 6: attestux.v1.ProtocolError.code:type_name -> attestux.v1.ProtocolErrorCode
	3,  // 7: attestux.v1.Frame.challenge:type_name -> attestux.v1.AttestationChallenge
	9,  // 8: attestux.v1.Frame.activation_challenge:type_name -> attestux.v1.CredentialActivationChallenge
	10, // 9: attestux.v1.Frame.activation_response:type_name -> attestux.v1.CredentialActivationResponse
	11, // 10: attestux.v1.Frame.receipt:type_name -> attestux.v1.VerificationReceipt
	12, // 11: attestux.v1.Frame.error:type_name -> attestux.v1.ProtocolError
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_attestux_v1_wire_proto_init() }
func file_attestux_v1_wire_proto_init() {
	if File_attestux_v1_wire_proto != nil {
		return
	}
	file_attestux_v1_wire_proto_msgTypes[10].OneofWrappers = []any{
		(*Frame_Challenge)(nil),
		(*Frame_Evidence)(nil),
		(*Frame_ActivationChallenge)(nil),
		(*Frame_ActivationResponse)(nil),
		(*Frame_Receipt)(nil),
		(*Frame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestux_v1_wire_proto_rawDesc), len(file_attestux_v1_wire_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_attestux_v1_wire_proto_goTypes,
		DependencyIndexes: file_attestux_v1_wire_proto_depIdxs,
		EnumInfos:         file_attestux_v1_wire_proto_enumTypes,
		MessageInfos:      file_attestux_v1_wire_proto_msgTypes,
	}.Build()
	File_attestux_v1_wire_proto = out.File
	file_attestux_v1_wire_proto_goTypes = nil
	file_attestux_v1_wire_proto_depIdxs = nil
}
